# Generated by Django 2.1.5 on 2021-08-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(default='author', max_length=256)),
                ('img', models.URLField()),
                ('publisher', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('publish_date', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('book_type', models.CharField(max_length=256)),
                ('ISBN', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.CharField(default='', max_length=8192)),
                ('category', models.CharField(default='', max_length=8192)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('book', models.ManyToManyField(to='rango.BookDetail')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('book', models.ManyToManyField(to='rango.BookDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=255)),
                ('total_price', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('isComment', models.IntegerField(default=0)),
                ('order_no', shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid1, editable=False, max_length=22)),
                ('book', models.ManyToManyField(to='rango.BookDetail')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookdetail',
            name='categories',
            field=models.ManyToManyField(to='rango.Category'),
        ),
    ]
