# Generated by Django 2.1.5 on 2021-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='author',
            field=models.CharField(default='author', max_length=256),
        ),
    ]
