# Generated by Django 2.1.5 on 2021-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_bookdetail_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
