# Generated by Django 2.1.5 on 2021-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_bookdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
