# Generated by Django 2.1.5 on 2021-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210802_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='desc',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
