# Generated by Django 2.1.5 on 2021-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_bookdetail_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='category',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
