# Generated by Django 2.1.5 on 2021-08-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_bookdetail_category'),
        ('rango', '0007_order'),
    ]

    operations = [
    ]
