# Generated by Django 2.1.5 on 2021-08-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20210805_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isComment',
            field=models.IntegerField(default=0),
        ),
    ]
