# Generated by Django 2.1.5 on 2021-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_order_iscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('book', models.ManyToManyField(to='rango.BookDetail')),
            ],
        ),
    ]
